inherit_from: .rubocop_todo.yml

# Turn this off for now. CI checks different versions of ruby anyway.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'zip-container.gemspec'

# Turn this off for certain files where we have extra documentation
# towards the end of the file, after a block of private methods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/zip-container/file.rb'
    - 'lib/zip-container/dir.rb'

# Force ruby19 style hash keys, but be consistent within a hash.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# I think 'has_key?' looks better than 'key?'.
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Allow long lines in the tests.
Metrics/LineLength:
  Exclude:
    - 'lib/zip-container/dir.rb'
    - 'test/**/*.rb'

# Ignore ABC failures in the tests.
Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

# Ignore block length failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable method length and ignore failures in the tests.
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable class length and ignore failures in the tests.
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
