inherit_from: .rubocop_todo.yml

# Turn this off for now. CI checks different versions of ruby anyway.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'zip-container.gemspec'

# Turn this off for now. I think we can't enable this until rubyzip
# does, and respects it, too.
Style/FrozenStringLiteralComment:
  Enabled: false

# Turn this off for certain files where we have extra documentation
# towards the end of the file, after a block of private methods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/zip-container/file.rb'
    - 'lib/zip-container/dir.rb'

# Force ruby19 style hash keys, but be consistent within a hash.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# I think 'has_key?' looks better than 'key?'.
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Exclude this file for now. Guard clauses in this file would be
# overly clunky at the moment.
Style/GuardClause:
  Exclude:
    - 'lib/zip-container/file.rb'

# Enforce empty lines at the beginning of classes.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

# Allow empty lines, or not, around module bodies. I like a line at the
# beginning, but not the end, but this is not an option in RuboCop.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow long lines in the tests.
Metrics/LineLength:
  Exclude:
    - 'lib/zip-container/dir.rb'
    - 'test/**/*.rb'

# Ignore ABC failures in the tests.
Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

# Ignore block length failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable method length and ignore failures in the tests.
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable class length and ignore failures in the tests.
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
