name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout zip-container code
      uses: actions/checkout@v4

    - name: Install and set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Rubocop
      run: bundle exec rubocop
